/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agenda;

import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author zoiloreyes
 */
public class Agenda extends javax.swing.JFrame {
    ContactoCRUD cc;
    ResultSet res;
    ListaContacto ls;
    JScrollPane sp;
    
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        prepareFullList();
        initComponents();
        prepareAgenda();
        
    }
    private void prepareAgenda(){
        setLayout(new BorderLayout());
        sp = new JScrollPane(ls);
        add(sp, BorderLayout.CENTER);
        add(new SearchBar(this), BorderLayout.NORTH);
        setVisible(true);
    }
    
    public void updateFrame(){
        prepareFullList();
        getContentPane().removeAll();
        prepareAgenda();
        revalidate();
    }
    
    public void prepareFilteredList(ResultSet res){
        try{ls = new ListaContacto();
            while(res.next()){
                int id_contacto = res.getInt(1);
                       String nombre = res.getString(2);
                       String apellido = res.getString(3);
                       String lugar = res.getString(4);
                       String telefono = res.getString(5);
                       String correo = res.getString(6);
                       String imagen = res.getString(7);


                       Contacto c = new Contacto(nombre, apellido, lugar, telefono, correo, imagen, id_contacto,this);
                       ls.addContacto(c);
            }
            getContentPane().remove(sp);
            JScrollPane sp = new JScrollPane(ls);
            add(sp, BorderLayout.CENTER);
            revalidate();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }
    
    private void prepareFullList(){
        try{
               cc = new ContactoCRUD();
               res = cc.getContactoFull();
               ls = new ListaContacto();
               Contacto nuevo = new Contacto("Nuevo","Contacto",null,null,null,"http://www.accurate-cutting.co.uk/wp-content/uploads/2014/06/plus-sign-150x150.jpg", -1,this);
               ls.addContacto(nuevo);
               while (res.next()){
                   int id_contacto = res.getInt(1);
                   String nombre = res.getString(2);
                   String apellido = res.getString(3);
                   String lugar = res.getString(4);
                   String telefono = res.getString(5);
                   String correo = res.getString(6);
                   String imagen = res.getString(7);
               
                   
                   Contacto c = new Contacto(nombre, apellido, lugar, telefono, correo, imagen, id_contacto,this);
                   ls.addContacto(c);
               }
               
               
           } catch (SQLException ex) {
               Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
