/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Agenda;

import java.awt.GridLayout;

/**
 *
 * @author zoiloreyes
 */
public class ListaContacto extends javax.swing.JPanel {
private int counter;
private GridLayout gl;
    /** Creates new form ListaContacto */
    public ListaContacto() {
        counter = 1;
        initComponents();
        
    }
    
    public void addContacto(Contacto c){
        gl = new GridLayout();
        gl.setRows(counter);
        setLayout(gl);
        add(c);
        revalidate();
        counter++;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(200, 60));
        setPreferredSize(new java.awt.Dimension(0, 600));
        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
