/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agenda;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zoiloreyes
 */
public class ShowContact extends javax.swing.JPanel {
    private String nombre;
    private String apellido;
    private String lugar;
    private String telefono;
    private String correo;
    private String url;
    private int id_contacto;
    private Imagen imgclass;
    private JFrame jf;
    private ContactoCRUD cc;
    private Agenda mother;
    private EditFrame ef;
    private UpdateContacto uc;

    /**
     * Creates new form ShowContact
     */
    public ShowContact(String nombre, String apellido, String lugar, String telefono,String correo, String url, int id_contacto,JFrame jf,Agenda mother) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.lugar = lugar;
        this.telefono = telefono;
        this.correo = correo;
        this.url = url;
        this.id_contacto = id_contacto;
        this.jf = jf;
        this.mother = mother;
        imgclass = new Imagen();
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblImagen = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTrabajo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true));
        setMinimumSize(new java.awt.Dimension(350, 454));
        setPreferredSize(new java.awt.Dimension(350, 454));
        setLayout(new java.awt.GridBagLayout());

        lblImagen = imgclass.getRoundImage(url, 100, 100, 6);
        lblImagen.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 76;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(lblImagen, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jLabel6, gridBagConstraints);

        lblNombre.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(102, 102, 102));
        lblNombre.setText(this.nombre + " " + this.apellido);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(lblNombre, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Lugar de trabajo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jLabel3, gridBagConstraints);

        lblTrabajo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblTrabajo.setForeground(new java.awt.Color(102, 102, 102));
        lblTrabajo.setText(this.lugar);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(lblTrabajo, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Telefono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jLabel4, gridBagConstraints);

        lblTelefono.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(102, 102, 102));
        lblTelefono.setText(this.telefono);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(lblTelefono, gridBagConstraints);

        lblNombre3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblNombre3.setForeground(new java.awt.Color(51, 153, 255));
        lblNombre3.setText("Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(lblNombre3, gridBagConstraints);

        lblCorreo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(102, 102, 102));
        lblCorreo.setText(this.correo);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(lblCorreo, gridBagConstraints);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(btnEditar, gridBagConstraints);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(jButton2, gridBagConstraints);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(btnSalir, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        jf.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] opciones = {"Cancelar", "Confirmar"};
        int response = JOptionPane.showOptionDialog(null, "Quiere eliminar el contacto?", "Eliminar",
        0, JOptionPane.QUESTION_MESSAGE,null,opciones, null);
        if (response == 0) {
        } else if (response == 1) {
          cc = new ContactoCRUD();
          cc.deleteContacto(id_contacto);
          JOptionPane.showMessageDialog(null,
            "El contacto ha sido eliminado");
          jf.dispose();
          mother.updateFrame();
        } else if (response == JOptionPane.CLOSED_OPTION) {
          
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ef = new EditFrame();
          uc = new UpdateContacto(this.nombre,this.apellido,this.lugar,this.telefono,this.correo,this.url,id_contacto,ef,mother);
          ef.add(uc);
          ef.setVisible(true);
          ef.revalidate();
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTrabajo;
    // End of variables declaration//GEN-END:variables
}
