/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agenda;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author zoiloreyes
 */
public class UpdateContacto extends javax.swing.JPanel {
    private String nombre;
    private String apellido;
    private String lugar;
    private String telefono;
    private String correo;
    private String url;
    private int id_contacto;
    private Agenda mother;
    private JFrame jf;
    private Component container;
    private ContactoCRUD cc;
    /**
     * Creates new form UpdateContacto
     */
    public UpdateContacto(String nombre, String apellido, String lugar, String telefono,String correo, String url, int id_contacto,JFrame jf, Agenda mother) {
       this.nombre = nombre;
        this.apellido = apellido;
        this.lugar = lugar;
         if(telefono != null && telefono.length() >= 14){
             this.telefono = telefono.substring(1,4) + telefono.substring(6,9) + telefono.substring(10,14);
        }
        this.correo = correo;
        this.url = url;
        this.id_contacto = id_contacto; 
        this.mother = mother;
        this.jf = jf;
        System.out.println(id_contacto);
        
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmar = new javax.swing.JButton();
        txtCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Link a imagen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        add(jLabel2, gridBagConstraints);

        txtUrl.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtUrl.setText(this.url);
        txtUrl.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 9;
        add(txtUrl, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        add(jLabel3, gridBagConstraints);

        txtNombre.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtNombre.setText(this.nombre);
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 9;
        add(txtNombre, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        add(jLabel4, gridBagConstraints);

        txtApellido.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtApellido.setText(this.apellido);
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 9;
        add(txtApellido, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Lugar de Trabajo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        add(jLabel5, gridBagConstraints);

        txtLugar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtLugar.setText(this.lugar);
        txtLugar.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 9;
        add(txtLugar, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("Telefono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        add(jLabel6, gridBagConstraints);

        txtTelefono.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtTelefono.setText(this.telefono);
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 9;
        add(txtTelefono, gridBagConstraints);

        txtCorreo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        txtCorreo.setText(this.correo);
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 9;
        add(txtCorreo, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("Correo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        add(jLabel7, gridBagConstraints);

        txtConfirmar.setText("Confirmar");
        txtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(txtConfirmar, gridBagConstraints);

        txtCancelar.setText("Cancelar");
        txtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(txtCancelar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarActionPerformed
        cc = new ContactoCRUD();
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        lugar = txtLugar.getText();
        correo = txtCorreo.getText();
        url = txtUrl.getText();
        telefono = txtTelefono.getText();
        container = SwingUtilities.getWindowAncestor(this);
        if(this.url.length() > 299){
            JOptionPane.showMessageDialog(jf,
            "Links deben ser menores a 300 carácteres",
            "Entrada inválida",
            JOptionPane.WARNING_MESSAGE);
        }else if(this.telefono.length() != 10){
            JOptionPane.showMessageDialog(jf,
            "El número de teléfono no tiene 10 digitos",
            "Entrada inválida",
            JOptionPane.WARNING_MESSAGE);
        }else if(this.nombre.length() == 0){
            JOptionPane.showMessageDialog(jf,
            "El nombre no puede estar vacío",
            "Campo vacío",
            JOptionPane.ERROR_MESSAGE);
        }
        else{
            cc.updateContacto(nombre, apellido, lugar, telefono, correo, url, id_contacto);
            JOptionPane.showMessageDialog(null,
            "El contacto ha sido actualizado");
            jf.dispose();
             
            mother.updateFrame();
        }
    }//GEN-LAST:event_txtConfirmarActionPerformed

    private void txtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelarActionPerformed
        jf.dispose();
    }//GEN-LAST:event_txtCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JButton txtCancelar;
    private javax.swing.JButton txtConfirmar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
